allowBuilds:
  esbuild: true
  spawn-sync: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
  vite-plus: 0.0.0-commit.6d65e1780791e2b24b27cf7deb63f57a420e78de
  vitest: 4.1.11
overrides:
  web-ext@^10.1.0>addons-linter: '-'
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
