allowBuilds:
  esbuild: true
  spawn-sync: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  vite-plus: 0.0.0-commit.16f3018f31dd475daf775e87e3eeb870fe9e5b4d
  vitest: 4.1.10
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
  web-ext@^10.1.0>addons-linter: '-'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
